# Generated by Django 5.0.4 on 2024-04-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-created'], 'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
    ]
