# Generated by Django 5.0.4 on 2024-04-19 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='defaultdays',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Leave days per year counter'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='enddate',
            field=models.DateField(help_text='coming back on ...', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leavetype',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave'), ('study', 'Study Leave'), ('maternity', 'Maternity Leave'), ('bereavement', 'Bereavement Leave'), ('quarantine', 'Self Quarantine'), ('compensatory', 'Compensatory Leave'), ('sabbatical', 'Sabbatical Leave')], default='sick', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(blank=True, help_text='add additional information for leave', max_length=255, null=True, verbose_name='Reason for Leave'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='startdate',
            field=models.DateField(help_text='leave start date is on ..', null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
