# Generated by Django 5.0.4 on 2024-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_leave_balance',
            field=models.IntegerField(default=0),
        ),
    ]
