# Generated by Django 5.0.4 on 2024-04-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_total_leave_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='total_leave_balance',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', upload_to='build/images/'),
        ),
    ]
