# Generated by Django 5.0.4 on 2024-04-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_grouppassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPassword',
        ),
    ]
